baseURL = 'https://hamana.nl/'
languageCode = 'nl-nl'
title = 'Cattery Hamana'
defaultContentLanguage = 'nl'
enableRobotsTXT = true

[params]
description = "Kleinschalige Ragdoll & Noorse Boskat-cattery in Arnhem die zich inzet voor het fokken van sociale en gezonde kittens."

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1

  [[menu.main]]
    identifier = 'niews'
    name = 'Nieuws'
    url = '/nieuws/'
    weight = 2

  [[menu.main]]
    identifier = 'kittenbeleid'
    name = 'Kittenbeleid'
    url = '/kittenbeleid/'
    weight = 3

  [[menu.main]]
    identifier = 'kittens'
    name = 'Kittens'
    url = '/kittens/'
    weight = 4

  [[menu.main]]
    identifier = 'onze-poezen'
    name = 'Onze poezen'
    url = '/onze-poezen/'
    weight = 5

  [[menu.main]]
    identifier = 'faq'
    name = 'FAQ'
    url = '/faq/'
    weight = 6

[imaging]
anchor = 'Smart'
bgColor = '#ffffff'
hint = 'photo'
quality = 75
resampleFilter = 'Box'
